default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5433
  username: postgres
  password: postgres

development:
  <<: *default
  database: quotebuilder_development

test:
  <<: *default
  database: quotebuilder_test

production:
  <<: *default
  database: quotebuilder_production
  username: <%= ENV["QUOTEBUILDER_DATABASE_USERNAME"] %>
  password: <%= ENV["QUOTEBUILDER_DATABASE_PASSWORD"] %>
